import { useContext } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { AuthContext } from "../context/AuthContext";
import { SnackbarContext } from "../context/SnackbarContext";
import Card from "../components/card/Card";
import { Container } from "@mui/material";
import FloatingAddButton from "../components/floatingActionButton/FloatingAddButton";

const Home: NextPage = () => {
  const { isSignedIn, currentUser } = useContext(AuthContext);
  const { triggerSnackbar } = useContext(SnackbarContext);

  console.log(isSignedIn, currentUser);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <br />
        <br />
        <button
          onClick={() => triggerSnackbar("error", "This is test message")}
        >
          snack me
        </button>
        <br />
        <br />
        <br />
        <Card />
      </Container>
      {isSignedIn && <FloatingAddButton />}
    </div>
  );
};

export default Home;
